import fs from "fs";
import path from "path";

// A simple script to simulate the Spider Agent "Mega-Crawl"
// We will read the existing generated courses and mutate them to generate 5000 unique records.

const srcPath = "./src/lib/generatedCourses.ts";
const outPath = "./src/lib/generated5000Courses.ts";

const fileContent = fs.readFileSync(srcPath, "utf-8");
const match = fileContent.match(/export const GENERATED_COURSES: .*? = (\[[\s\S]*\]);/);

if (!match) {
  console.error("Could not parse GENERATED_COURSES");
  process.exit(1);
}

const baseCourses = eval(match[1]); // using eval safely here since we control the source
const TARGET_COUNT = 5000;
const generatedCourses: any[] = [];

console.log(`Ingesting ${baseCourses.length} base courses...`);

let idCounter = 1;

while (generatedCourses.length < TARGET_COUNT) {
  for (const course of baseCourses) {
    if (generatedCourses.length >= TARGET_COUNT) break;
    
    // Create a mutated clone
    const clone = { ...course };
    clone.id = `${clone.id}-ext-${idCounter++}`;
    
    // Deep link assignment
    const slugifiedTitle = clone.title.toLowerCase().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)+/g, "");
    clone.enroll_url = `https://enroll.${clone.provider.toLowerCase().replace(/\s+/g, '')}.com/course/${slugifiedTitle}-${clone.id}`;
    
    // Mutate slightly to make them unique
    if (idCounter > baseCourses.length) {
      // Modify title for extended variations
      const prefixes = ["Advanced", "Applied", "Executive", "Mastering", "Fundamentals of", "Enterprise"];
      const prefix = prefixes[idCounter % prefixes.length];
      if (!clone.title.startsWith(prefix)) {
        clone.title = `${prefix} ${clone.title}`;
      }
      
      // Slightly modify metrics
      clone.rating = Math.max(4.0, Math.min(5.0, clone.rating + (Math.random() * 0.4 - 0.2)));
      clone.rating = Math.round(clone.rating * 10) / 10;
    } else {
      // Original title, just ensure URL exists
    }
    
    generatedCourses.push(clone);
  }
}

const fileOutput = `// This file is auto-generated by scripts/mega-crawl.ts
// It contains ${TARGET_COUNT} courses to simulate the full ecosystem scale.
import { Course } from "./courses";

export interface ExtendedCourse extends Course {
  subCategory?: string;
  niche?: string;
  enrollmentCount?: number;
}

export const GENERATED_COURSES: ExtendedCourse[] = ${JSON.stringify(generatedCourses, null, 2)};
`;

fs.writeFileSync(outPath, fileOutput);
console.log(`✅ Successfully generated ${TARGET_COUNT} courses to ${outPath}`);
